### ISSUE TITLE
possible namespaces conflict

### ISSUE THREAD

**Issue by guisouza** [feliperochadev/check-js#1]
We could protect its namespaces functions by grouping it in an object using Module pattern.
Example : https://gist.github.com/guisouza/eb4a3ff8dbcb54c58555

**Comment by mauriciosoares** [comment]
Agreed,

Also when you assign a variable to the `this` inside an IIFE like you are doing it on line 49 for example, you are actually assigning it to the global scope.

You should check that out too.

**Comment by guisouza** [comment]
Yep @mauriciosoares . 

@feliperochadev check bind, apply, call and new behavior.

**Comment by feliperochadev** [comment]
I did code refactoring and applied the Module Pattern as @guisouza example, I created a new version (1.1) and put the 1.0 in a older version folder.

Check out the new version.

Thanks a lot, @guisouza and @mauriciosoares

**Comment by mauriciosoares** [comment]
Consider using **git tags** instead of "old" folders.

It makes things simpler for you to create your next builds and features.

**Comment by feliperochadev** [comment]
Good ideia @mauriciosoares i'll do that in nexts releases, thanks!
